- src/index.ts
Fixes plugin class compatibility
N/A
> fix: plugin class compatibility

- src/index.ts
> added recaptchaToken to InvokeRightRequest
Build completed successfully
(KD-5049)[https://ketch-com.atlassian.net/browse/KD-5049]
> fix: added recaptchaToken to InvokeRightRequest

- src/index.ts
> added recaptchaToken field to InvokeRight event
`npm run build` ran successfully
[KD-5343](https://ketch-com.atlassian.net/browse/KD-5343)
> fix: added recaptchaToken field to InvokeRight event

- src/index.ts
> remove recaptcha token from Invoke Right event
`npm run build` ran successfully w/o errors
> [KD-5343](https://ketch-com.atlassian.net/browse/KD-5343)
> fix: remove recaptcha token from Invoke Right event

- src/index.ts
> removed recaptchaEnabled from RightsTab. added token to event
`npm run build` ran successfully w/ errors
> [KD-5343](https://ketch-com.atlassian.net/browse/KD-5343)
> fix: removed recaptchaEnabled from RightsTab. added token to event

- package-lock.json
- package.json
- src/index.ts
Add read repair to consent
N/A
> feat: add read repair to get consent

- src/index.ts
> fix(identity): plugin get

- src/index.ts
> fix(identity): register identity name

- src/index.ts
> fix(identity): register identity string

- src/index.ts
Add provisional consent to `Ketch` interface
Unit tests
```
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |                   
index.ts |     100 |      100 |     100 |     100 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        2.672 s, estimated 3 s
```
> fix: provisional consent

- src/index.ts
Drop duplicate config language property
web-api
> fix: drop duplicate language prop

- src/index.ts
> Description here
subscription tab types
> fix: subscriptions tab

- src/index.ts
> fix: subscriptions close reason

- src/index.ts
> updated Rights Tab Config w/ form field config
[KD-6420](https://ketch-com.atlassian.net/browse/KD-6420)
[KD-6420]: https://ketch-com.atlassian.net/browse/KD-6420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: updated Rights Tab Config w/ form field config

- src/index.ts
> add formData to right invocation request body
[KD-6426](https://ketch-com.atlassian.net/browse/KD-6426)
[KD-6426]: https://ketch-com.atlassian.net/browse/KD-6426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add formData to right invocation request body

- src/index.ts
> add city to DataSubject
`npm run build` ran successfully and generated correct types
[KD-6847](https://ketch-com.atlassian.net/browse/KD-6847)
[KD-6847]: https://ketch-com.atlassian.net/browse/KD-6847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add city to DataSubject

- src/index.ts
showOverviewTab to toggle overview tab in lanyard
> fix: showOverviewTab

- src/index.ts
> Updates Theme types
https://www.loom.com/share/81c1920c0cee454389817bf79cdfcc29
https://ketch-com.atlassian.net/browse/KD-7024
> feat(KD-7023): Updates Theme types;

- src/index.ts
> updates Theme types;
https://www.loom.com/share/11d465c0e9c54f2cbdbe1b7f59eb25ef
https://ketch-com.atlassian.net/browse/KD-7025
> feat(KD-7025): Adds modal & form "background-color" to theme 

- src/index.ts
> updates form templates types
Validated locally in Lanyard via npm link;
https://ketch-com.atlassian.net/browse/KD-8225
> fix(KD-8225): updates form templates types;

- src/index.ts
> fix(config): plugin options

- src/index.ts
> fix(config): canonicalPurposeCodes

- src/index.ts
> fix: add 'banner_force_interaction' to themes
> `npm run build` ran successfully 
[KD-8883](https://ketch-com.atlassian.net/browse/KD-8883)
[KD-8883]: https://ketch-com.atlassian.net/browse/KD-8883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add 'banner_force_interaction' to themes

- .gitignore
- src/index.ts
> extend translations for recaptcha copy
> local development
> https://ketch-com.atlassian.net/browse/KD-9142
> feat(kd-9142): extend translations for lanyard recaptcha copy

- src/index.ts
> extend translations for recaptcha copy
> local dev
> https://ketch-com.atlassian.net/browse/KD-9142
> feat(kd-9142): extend translations for recaptcha copy

- src/index.ts
> relocate 'recaptchaEnabled' field
> `npm run build` ran successfully
> [KD-9249](https://ketch-com.atlassian.net/browse/KD-9249)
[KD-9249]: https://ketch-com.atlassian.net/browse/KD-9249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: relocate 'recaptchaEnabled' field

- src/index.ts
> fix(config): include v2 objects

- src/index.ts
> fix(config): separate v2 for dev

- src/index.ts
Property specific subscriptions feature introduces v2 api and data model changes for marketing preference orchestration
https://ketch-com.atlassian.net/browse/KD-10261
https://ketch-com.atlassian.net/browse/KD-10260
> feat: property specific subscriptions

- src/index.ts
> fix: subscription control unspecified type

- src/index.ts
> Updates config to reflect design updates
> feat: new action button use default config option

- src/index.ts
> Types that will be used in `ketch-web-api`
> feat: get config v2 request types

- src/index.ts
> Types for getConsentConfiguration and getPreferenceConfiguration
> feat: types for new config get functions

- src/index.ts
> Adds visible field for the unsubscribe from all form
> feat: add visible field for unsubscribe all

- src/index.ts
> Adds org code to request interfaces for v2 config calls
> feat: add org code to config v2 request types

- src/index.ts
> feat: add name to subscription item type

- src/index.ts
> Update preference page type names
> chore: update pref page names

- src/index.ts
> Adds content and layout config types for the action button in the pref center > requests > form section
> feat: request form action button experience types

- src/index.ts
> Adds error state theme configs for checkbox
> feat: checkbox error state theme config

- src/index.ts
- Renames and fixes restructures various fields, @keepforever notably:
- Restructures preference center theme and experience configs to have a `tabs` field which contains the configs for each tab, then configs applying to the whole preference center are on the outermost level. See [here](https://github.com/ketch-sdk/ketch-types/pull/163/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R3383-R3390), [here](https://github.com/ketch-sdk/ketch-types/pull/163/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R3383-R3390), and [here](https://github.com/ketch-sdk/ketch-types/pull/163/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R4086-R4095)
- "Powered by Ketch" badge config moved to theme, see …
> chore: refactor config

- src/index.ts
> fix(consent): include protocols

- src/index.ts
> Remove name field (will get name off subscription in FH using code)
> chore: remove subscription name

- src/index.ts
> chore: simplify type to remove double title key

- src/index.ts
> adds new events needed for mobile sdk
w/ new ketch tag events fired from lanyard 
https://ketch-com.atlassian.net/browse/KD-10640
> feat: add new events needed for mobile sdk

- src/index.ts
> Adds outline field that was missed
> chore: add outline field

- src/index.ts
> fix: experience display

- src/index.ts
> Change `defaultFormId` to `defaultFormCode`
> fix: default form name

- src/index.ts
> Changes all instances of `formCode` to `formID`
> chore: change formCode to formID

- src/index.ts
> Message type for sending preview configs from figurehead to lanyard
> feat: preview message type

- src/index.ts
> Updates structure and adds preview message types to reflect what is expected by lanyard
> feat: update preview type

- src/index.ts
> Adds static text key for the word "save"
> feat: add static text "save"

- src/index.ts
> feat: additional translations keys

- src/index.ts
> chore: add translation

- src/index.ts
> add translation when no rights are available
Local
https://ketch-com.atlassian.net/browse/KD-11437
> feat: no rights translation

- src/index.ts
> Adds entitlement flags to experience layout config
- https://ketch-com.atlassian.net/browse/KD-11430
> feat: add entitlements info to config

- src/index.ts
> fix(consent): set response

- src/index.ts
> fix(protocol): type

- src/index.ts
> fix(setConsent): reason

- src/index.ts
Option to  disable consent capture
locally
https://ketch-com.atlassian.net/browse/KD-12170
https://ketch-com.atlassian.net/browse/KD-12048
> feat: orchestration only

- src/index.ts
> Move exit button position config from theme config to experience config
- https://ketch-com.atlassian.net/browse/KD-12035
> fix: move exitPosition to experience

- src/index.ts
> Add cornerRadius attribute to PreferenceExitButton type
tested locally
https://ketch-com.atlassian.net/browse/KD-11575
> fix: Add cornerRadius to PreferenceExitButton

- src/index.ts
> add banner button action open url enum value
tested locally
https://ketch-com.atlassian.net/browse/KD-13158
> fix: banner button action open url

- src/index.ts
> Add optional consent field to the experienceClosed method and un-deprecate
> fix: update experienceClosed method signature

- src/index.ts
> fix(config):identity encoding

- src/index.ts
> Added types for FAB Button
tested locally
https://ketch-com.atlassian.net/browse/KD-13214
> [KD-13214] - FAB Button

- src/index.ts
chore: added tags type to the ConfigurationV2
> chore: added tags type to the ConfigurationV2

- src/index.ts
> fix: consent options

- src/index.ts
chore: added blocked cookie type
> chore: added blocked cookie type

- src/index.ts
> Adjusts the `blockedCookies` key of the config to match what supercargo returns in config.json
> fix: blockedCookies type

- src/index.ts
> Removes unused pattern field and makes regex optional, we assume exact match on cookieKey if regex not defined
> fix: remove pattern and make regex optional in config.blockedCookies

- src/index.ts
> Adds missing options field in plugin options
- https://ketch-com.atlassian.net/browse/KD-14050
> fix: add options field

- src/index.ts
Add systems field to config type
Local
> chore(types): add systems field to config type

- .github/workflows/ci.yml
> Updates `ci.yml` to node v20
- https://ketch-com.atlassian.net/browse/KD-14170
> chore: upgrade to node v20

- src/index.ts
> Adds fields for progressive consent experiences and themes - will update these with actual structure one we know
- https://ketch-com.atlassian.net/browse/KD-14180
> feat: stub fields for progressive consent experiences/themes (JIT)

- src/index.ts
> Removes unused field which we don't use
> chore: remove unused experience display type

- src/index.ts
> Switch the `ConfigurationV2` type to use a `CombinedExperienceConfig` which supports multiple progressive consent experiences. Will add the structure of these PC experiences later
> feat(pc): multiple pc experiences in a single configuration

- src/index.ts
> Simplifies config type for progressive experiences and adds all types
> feat: progressive experience types

- src/index.ts
> Types for embedding experience on page
> feat(progressive consent): types for embedded JIT

- src/index.ts
> Add purpose codes to switch button config
> feat: add purpose codes to switch button config

- src/index.ts
> Add always on text config option
- https://ketch-com.atlassian.net/browse/KD-14295
> feat(hearst): always on switch config

- src/index.ts
> fix: vendor illustrations

- src/index.ts
> fix: tcf systems

- src/index.ts
> Add experience display type to fab button
> feat(application): add experience display type to fab button

- src/index.ts
vendor retention and declaration
locally
https://ketch-com.atlassian.net/browse/KD-14336
https://ketch-com.atlassian.net/browse/KD-14337
> fix: vendor retention and declaration

- src/index.ts
> fix: tcf vendors

- src/index.ts
> fix: device storage translations

- src/index.ts
> Adds profile tab to enum so it can be opened initially via `ketch_preferences_tab=profileTab`
> feat: add profile tab

- src/index.ts
> Updates config type to differentiate between auto and user initiated experiences
- https://ketch-com.atlassian.net/browse/KD-14736
> feat(experiences): auto vs user initiated

- src/index.ts
> Types for new `showExperience` function
- https://ketch-com.atlassian.net/browse/KD-14736
> feat: showExperience function

- src/index.ts
> Removes old showExperience type
> fix: remove old show experience

- src/forms.ts
support file type in rights form
locally
> fix: file type

- src/index.ts
- Banner/modal header and footer images
- Option to hide accept/reject all buttons and configure text
> feat(experiences): banner/modal images and hide buttons

- src/index.ts
> fix: cloudinary translations

- src/index.ts
> Configuration of vendors in experience. Also sets sockets for configuration of other subpages (e.g. cookies, illustrations, etc.)
- https://ketch-com.atlassian.net/browse/KD-14739
> feat(experiences): vendor configuration

- src/index.ts
> Adds array of installed system ids
- https://ketch-com.atlassian.net/browse/KD-14739
> feat(experiences): associated system ids

- src/index.ts
> fix(experiences): associated entity key names

- src/index.ts
> Add vendor translation fields
> feat(translations): add vendor translation fields to BaseStaticContentConfig

- src/index.ts
> Specify types for each system variant
> feat: explicit system types

- src/index.ts
Frontend counterpart to https://github.com/ketch-com/api/pull/777 so we can use these fields in the client-side tcf impl in ketch-plugins
Local
https://github.com/ketch-com/api/pull/777/files
> chore(config): pub restrictions fields to vendor purpose

- src/index.ts
> Adds view_privacy_policy translation key
> fix: view_privacy_policy translation key

- src/index.ts
> chore: translations

- src/index.ts
> Updates getConsent method type to have noCache flag
> feat: noCache flag in getConsent

- src/forms.ts
> fix: form section conditions

- src/forms.ts
> fix: section conditions

- src/index.ts
> fix: protocolOnly param name

- src/index.ts
Persistent/Session cookie types
> chore: types

- src/index.ts
Allow for opting out of legitimate interest on a purpose and a vendor level
Local
https://ketch-com.atlassian.net/browse/KD-15150
> chore(tcf): add purpose & vendor leg ints to consent object

- src/index.ts
> feat: deployment experience type

- src/index.ts
- Adds a context object to permit (consent and subscription) and rights requests/responses
- Moves GPC enabled to this context object
> feat: permit/right context

- src/index.ts
> Type tweaks for permit context
> chore: types for permit context

- src/index.ts
> fix: setConsent signature

- src/index.ts
> feat: source in setSubscriptions

- src/index.ts
> feat: progressive-consent-source

- src/index.ts
> Adds new subscriptions source
> feat: router.setSubscriptions source

- src/index.ts
updating `ConsentSource` to know if consent persisted via optin/optout method
> chore: update ConsentSource  enum

- src/index.ts
> chore: accept/reject all

- src/index.ts
> consent source for ot migrator
> feat: ot migrator consent source

- src/index.ts
add regionCode to InvokeRightRequest
> chore: add regionCode to InvokeRightRequest

- src/index.ts
> fix: saveandclose

- src/index.ts
> Progressive consent rules added to ConfigurationV2, along with the Rule types (conditions, action, etc.) and banner dismiss options. As part of this change, some additions were made to the experience config, so that lanyard can use an experience ID to determine which experience to show. Changes also made to the Consent Gate configuration interfaces to align with design and available choices for theme and experience (layout/content).
> feat(progressive): add Rules config and affiliated types

- src/index.ts
> Minor fix to use proper Profile key structure and consent gate config
> fix: update profile key structure

- src/index.ts
> Adds static translation keys for GPC banner content
> feat: add keys for GPC banner text

- src/index.ts
> Adds experience types to config
> feat: add experience types to config

- src/index.ts
> Fixes config, uses proper type in consent gate consent block header / purposes list header
> fix: theme type

- src/index.ts
> chore: gpc banner
